version: '3.3'

services:

  elasticsearch_master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    #restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config_master
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      #- bootstrap.memory_lock=true
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #ulimits:
      #memlock:
        #soft: -1
        #hard: -1
    volumes:
      - esmaster:/usr/share/elasticsearch/data
    networks:
      - es
    deploy:
      mode: replicated
      replicas: 3

elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    #restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config_data
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      #- bootstrap.memory_lock=true
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #ulimits:
      #memlock:
        #soft: -1
        #hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es
    deploy:
      mode: global

  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    ports:
      - "5000:5044"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - es
    deploy:
      mode: replicated
      replicas: 1

      
configs:

  elastic_config_master:
    file: ./elasticsearch/config4_master/elasticsearch.yml
  elastic_config_data:
    file: ./elasticsearch/config4_data/elasticsearch.yml
  logstash_config:
    file: ./logstash/config4/logstash.yml
  logstash_pipeline:
    file: ./logstash/pipeline4/logstash.conf
  kibana_config:
    file: ./kibana/config4/kibana.yml
 
volumes:
  esdata:
    driver: local
  esmaster:
    driver: local  
    
networks:
  es:
    driver: overlay
