version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    #restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      #- bootstrap.memory_lock=true
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #ulimits:
      #memlock:
        #soft: -1
        #hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es
    deploy:
      mode: global

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
 
volumes:
  esdata:
    driver: local
    
networks:
  es:
    driver: overlay
