version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es
    deploy:
      mode: replicated
      replicas: 3

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
 

networks:
  es:
    driver: overlay
